#!/sbin/busybox sh

# $1 - "scaling_max_freq"
# $2 - value=
# Created By Dorimanx

# get values from profile
PROFILE=$(cat /data/.imperium/.active.profile);
. /data/.imperium/"$PROFILE".profile;

if [ "a$2" != "a" ]; then
	scaling_max_freq=$2;

	echo "$scaling_max_freq" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq;
	echo "$scaling_max_freq" > /sys/devices/system/cpu/cpu1/cpufreq/scaling_max_freq;
	echo "$scaling_max_freq" > /sys/devices/system/cpu/cpu2/cpufreq/scaling_max_freq;
	echo "$scaling_max_freq" > /sys/devices/system/cpu/cpu3/cpufreq/scaling_max_freq;
fi;

echo ${scaling_max_freq};
