#!/sbin/busybox sh

. /res/customconfig/customconfig-helper

_ACTIVEPROF=`cat /data/.imperium/.imperium.profile`

case "${_ACTIVEPROF}" in
  battery)
    cp /data/.imperium/battery.profile /data/.imperium/default.profile 
    read_defaults
    read_config
    apply_config
    ;;
  balanced)
    cp /data/.imperium/balanced.profile /data/.imperium/default.profile 
    read_defaults
    read_config
    apply_config
    ;;
  performance)
    cp /data/.imperium/performance.profile /data/.imperium/default.profile 
    read_defaults
    read_config
    apply_config
    ;;
esac;
