#!/sbin/busybox sh

if [ "a$2" != "a" ];then

filename=$(basename $2)

if [ "a$3" == "a" ];then
  evalcmd='eval "echo \$$filename"'
  eval $evalcmd
else
  evalcmd='eval "$filename=$3"'
  eval $evalcmd
  evalcmd='eval "echo \$$filename"'
  eval $evalcmd
  
case "$hotplug" in

  0)
        echo "0" > /sys/module/intelli_plug/parameters/intelli_plug_active
	start mpdecision
	echo "MPDecision enabled"
  ;; 
  1)
        stop mpdecision
        echo "1" > /sys/module/intelli_plug/parameters/intelli_plug_active
	echo "Intelli-Plug enabled"
  ;;
esac;

fi
fi
