#!/sbin/busybox sh

# $1 - "scaling_governor_cpu0"
# $2 - value=
# Created By Dorimanx

# get values from profile
PROFILE=$(cat /data/.imperium/.active.profile);
. /data/.imperium/"$PROFILE".profile;

if [ "a$2" != "a" ]; then
	scaling_governor_cpu0=$2;

	echo "$scaling_governor_cpu0" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor;
	echo "$scaling_governor_cpu0" > /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor;
	echo "$scaling_governor_cpu0" > /sys/devices/system/cpu/cpu2/cpufreq/scaling_governor;
	echo "$scaling_governor_cpu0" > /sys/devices/system/cpu/cpu3/cpufreq/scaling_governor;
fi;

echo ${scaling_governor_cpu0};
